body = input()
print("<html>")
print("<head>")
print("<title> First CGI Program</title>")
print("</head>")
print("<body>")
print("<h2>Python</h2>")
if body != "":
    print("<h1>" + body + "<h1>")
print("</body>")
print("</html>")
